// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAezj651I3pt6thfhQrXpR3EhbqtNR0-U',
    appId: '1:49403421832:web:4434b0ee521c1379c6ab3d',
    messagingSenderId: '49403421832',
    projectId: 'faith-connects-c7a7e',
    authDomain: 'faith-connects-c7a7e.firebaseapp.com',
    storageBucket: 'faith-connects-c7a7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUTa_mhWaKSnPtbZUGneXukDD7QIe7fk',
    appId: '1:49403421832:android:9877d202fb8f4c57c6ab3d',
    messagingSenderId: '49403421832',
    projectId: 'faith-connects-c7a7e',
    storageBucket: 'faith-connects-c7a7e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAezj651I3pt6thfhQrXpR3EhbqtNR0-U',
    appId: '1:49403421832:web:adcdb5eb0c4a9d80c6ab3d',
    messagingSenderId: '49403421832',
    projectId: 'faith-connects-c7a7e',
    authDomain: 'faith-connects-c7a7e.firebaseapp.com',
    storageBucket: 'faith-connects-c7a7e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBD0SYbAXLB6ICAVH4x4XY7lOVzy0sic',
    appId: '1:49403421832:ios:f444561956e473cbc6ab3d',
    messagingSenderId: '49403421832',
    projectId: 'faith-connects-c7a7e',
    storageBucket: 'faith-connects-c7a7e.firebasestorage.app',
    iosBundleId: 'com.example.christianMediaapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBD0SYbAXLB6ICAVH4x4XY7lOVzy0sic',
    appId: '1:49403421832:ios:f444561956e473cbc6ab3d',
    messagingSenderId: '49403421832',
    projectId: 'faith-connects-c7a7e',
    storageBucket: 'faith-connects-c7a7e.firebasestorage.app',
    iosBundleId: 'com.example.christianMediaapp',
  );

}